name: Deploy Hugging Face Space

on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub

      - name: Deploy Space to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN}}
          REPO_ID: 041022-wz/llama-fac
        run: |
          huggingface-cli upload-large-folder --path . --repo-id $REPO_ID --token $HF_TOKEN
